[tox]
envlist = py39, py310, py311, py312, black

[testenv]
deps =
    -rrequirements.txt
    -rrequirements-dev.txt
commands =
    py.test {posargs}

[testenv:black]
commands =
    black --check --target-version py39 --line-length 120 --color --diff .

[gh-actions]
python =
    3.9: py39, black
    3.10: py310
    3.11: py311
    3.12: py312
